### ISSUE TITLE
Move repository and set up Waffle

### ISSUE THREAD

**Issue by bajiat** [Dipor/platform#19]
Move the contents of this repository to Digipalvelutehdas. Invite all team members. Set up Dipor team in Digipalvelutehdas organization. Set up a Waffle board.

**Comment by jykae** [comment]
Created repo https://github.com/Digipalvelutehdas/dipor-dashboard and added @bajiat and @brylie as admin.

**Comment by bajiat** [comment]
This issue was moved to Digipalvelutehdas/dipor-dashboard#1

**Comment by bajiat** [comment]
This issue was moved to Digipalvelutehdas/dipor-dashboard#2
